# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef9f5eac020d39b7a01971175055c3c734b0d4675a764e66d0bf9c3eb94ff5ed86455356a4ccfe02fdd6b82d81ca0ef0241bad9d47216831c4114ce6c2a20e4

test:
  secret_key_base: 81650e15357248d6571ce49315541b37d811d282a765c9bb6b7c55c008d7abc5c9b89cbf16f448e23b471fe211ecb77ff53e58166f6a581e4802b03883852796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
